#Depending on the operating system of the host machines(s) that will build or run the containers, the image specified in the FROM statement may need to be changed.
#For more information, please see https://aka.ms/containercompat

FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /PartsUnlimitedWebsite
COPY PartsUnlimited.sln .
COPY src/*.csproj ./PartsUnlimitedWebsite/
RUN dotnet restore 

COPY PartsUnlimitedWebsite/. ./PartsUnlimitedWebsite/
WORKDIR /PartsUnlimitedWebsite
RUN dotnet publish -c release -o /app --no-restore


FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
WORKDIR /app
COPY --from=build /app ./
ENTRYPOINT ["dotnet", "PartsUnlimitedWebsite.dll"]

